### ISSUE TITLE
Update README to point to Aetf/libtsm as the dependency

### ISSUE THREAD

**Issue by tecfu** [Aetf/kmscon#14]
The latest version of libtsm is 3, see: https://cgit.freedesktop.org/~dvdhrm/libtsm/commit/?id=e998bb280049ccd477b50a35718abdb46ab6a9fc

However, configuration says: 

```
configure: error: Package requirements (libtsm >= 4.0.0) were not met:

Requested 'libtsm >= 4.0.0' but version of libtsm is 3
You may find new versions of libtsm at http://dvdhrm.github.io/libtsm

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables TSM_CFLAGS
and TSM_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by Aetf** [comment]
Hi,

Thanks for the help!

I intentionally bumped the required version to use my version of libtsm. And it's indeed creating some confusion due to the old README.

But could you update to keep the original README, i.e., creating a new file `README.md` and mention the old one via a link, like what I've done in libtsm?
