### ISSUE TITLE
Fails to build on current Arch Linux

### ISSUE THREAD

**Issue by Ranguvar** [Aetf/kmscon#17]
Hey Aetf!

I just stumbled across kmscon and would love to try it, thanks for your work here.

I just tried to compile this on Arch using your AUR PKGBUILD.

Here is my log: http://ix.io/1mda

**Comment by plntyk** [comment]
You do not seem to use the AUR pkgbuild of **kmscon-patched-git**

I think you might be using kmscon-git which is pointing to the non-forked original version which is currently not maintained and inactive.

**Comment by Aetf** [comment]
@Ranguvar 
Hmm, from your log it seems you are indeed building `kmscon-patched-git`.

Nothing immediately wrong from the log that I can find. But maybe somehow your build environment is messed up. There's line saying that your are using a custom linker:
```
checking for ld used by gcc... /home/ranguvar/bin/ld
```
Are you sure this is what you want?

**Comment by plntyk** [comment]
oh well I was confused by
[AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kmscon-patched-git)
containing
````
--disable-wlterm
````
But there is no configure warning in the log since wlterm was removed from kmscon in https://github.com/Aetf/kmscon/commit/695c855da33c3ef40bdd6e5bce7a6a78875a7af8
so there should be
````
configure: WARNING: unrecognized options: --disable-wlterm
````
Are these warnings disabled on your end ? Different automake version?


your log has
````
checking whether make supports the include directive... yes (GNU style)
````
my Arch outputs:
````
checking for style of include used by make... GNU
````

The
````
/bin/sh: line 1: -DHAVE_CONFIG_H: command not found
````
suggests that your _Makefile_ was generated with wrong values indicating something wrong with the autotools/automake setup and environment then.
I have for example
````
DEFS = -DHAVE_CONFIG_H
````
and the Makefile seems to use
````
$(CC) $(DEFS)
````
so $(CC) might be empty amd $(DEFS) is the first command.
You could run 
````
make V=99
````
on a local git checkout to see what commands are invoked.

**Comment by Ranguvar** [comment]
Yeah, removed the disable-wlterm line as it was doing nothing.

That ~/bin/ld exists to force use of the gold linker.

My apologies to everyone for wasting time, I had forgotten that I was using a git build of autoconf and automake.

Works fine with normal build tools!
