### ISSUE TITLE
[question] Is it possible to set a different background colour?

### ISSUE THREAD

**Issue by elkcl** [Aetf/kmscon#21]
I was able to change the colour scheme using "palette=solarized-black" in the config file, however, I couldn't find a way to change the background colour. Is it even possible with KMSCON?

Thanks in advance.

**Comment by thesmiley1** [comment]
As far as I know, this is not (currently) possible.  Neither the original author nor anyone else has implemented functionality to customize colors arbitrarily via configuration.  It should be straight-forward, just was never done.

There is something of a sister project to kmscon:  libtsm.  IIRC, the code for libtsm was extracted from the kmscon code fairly late in the project's life and the two are still fairly tightly-coupled.

I mention that because that is where the hard-coded color palettes live.  So if you would rather just hard-code your own color palette, here is an example:  https://github.com/thesmiley1/libtsm/commit/b7de2d1e582cd911ecb4ac3c74428ebf1969c048.

**Comment by elkcl** [comment]
Thank you, I managed to successfully add Oceanic Next as a colour palette
